apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-sc


