apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
rules:
- apiGroups: [""]
  resources:
    - pods
    - namespaces
    - nodes
    - events
  verbs: ["get", "watch", "list"]
