apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: {{ .Values.logstash.image }}
        ports:
        - containerPort: 5044
        env:
        - name: ES_USERNAME
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elastic-credentials
              key: password
        volumeMounts:
        - name: pipeline-config
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: pipeline-config
        configMap:
          name: logstash-pipeline


